### ISSUE TITLE
Typecheck playlist match that is being passed into PlaylistDetails

### ISSUE THREAD

**Issue by npdarrington** [bretm9/genrefy#68]
- [ ] Currently, on PlaylistDetails.tsx, when we declare the playlist in IProps with Playlist | undefined, it will throw typecheck errors on rendering the data to the page.

**Comment by bretm9** [comment]
This is a known typescript bug relating to union types. [See here](https://github.com/microsoft/TypeScript/issues/30271). We have verified the props coming in as `Playlist | []` so having to typing it to `any` here should be acceptable.
